services:
  postgres:
    image: postgres:latest
    container_name: etl_pipeline
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
