services:
  postgres:
    image: postgres:latest
    container_name: etl_pipeline
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    volumes:
      - ./seed_data:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
#    networks:
#      - etl_network
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U etl"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  etl-airflow:
    container_name: etl_airflow
    image: etl:latest
    volumes:
      - ./airflow:/opt/airflow
      - ./etl_pipeline:/opt/airflow/etl_pipeline
    ports:
      - "8080:8080"
    user: "${UID}:${GID}"
    environment:
      - AIRFLOW_UID=${UID}
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins &&
      chmod -R 777 /opt/airflow &&
      airflow standalone
      "
      

#    networks:
#      - etl_network
##    depends_on:
##      postgres:
##        condition: service_healthy

#networks:
#  etl_network:
#    driver: bridge
