version: 2

models:
  - name: fact_patient_visits
    description: "Fact table capturing the number of visits, total cost, and visit dates for each patient and doctor."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient."
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id
      - name: doctor_id
        description: "Unique identifier for the doctor."
        tests:
          - not_null
          - relationships:
              to: ref('dim_doctors')
              field: doctor_id
      - name: visit_count
        description: "Total number of visits by the patient to the doctor."
        tests:
          - not_null
      - name: total_cost
        description: "Sum of costs for all visits by the patient to the doctor."
        tests:
          - not_null
      - name: first_visit_date
        description: "Date of the patient's first visit to the doctor."
      - name: last_visit_date
        description: "Date of the patient's last visit to the doctor."

  - name: dim_patients
    description: "Dimension table containing patient details."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient."
        tests:
          - not_null
          - unique
      - name: patient_name
        description: "Full name of the patient."

  - name: dim_doctors
    description: "Dimension table containing doctor details."
    columns:
      - name: doctor_id
        description: "Unique identifier for the doctor."
        tests:
          - not_null
          - unique
      - name: doctor_name
        description: "Full name of the doctor."
      - name: specialization
        description: "Specialization of the doctor."
