version: 2

# defining the sources
sources:
  - name: trans #logical name for the source
    schema: public # name of the schema
    tables:
      - name: staging_patient_visits
        description: "raw data tha is loaded from teh csv"
        columns:
          - name: patient_id
            description: "Unique identifier for each patient."
            tests:
              - not_null
models:
  - name: dim_patients
    description: "Dimension table containing patient information"
    columns:
      - name: patient_id
        description: "Unique identifier for each patient."
        tests:
          - not_null
          - unique
      - name: patient_name
        description: "Full name of the patient."
        tests:
          - not_null
  - name: dim_doctors
    description: "Dimension table containing doctor information"
    columns:
      - name: doctor
        description: "Full name of the doctor"
        tests:
          - not_null
      - name: department
        description: "Specialization of the doctor"
        tests:
          - not_null
  - name: dim_bra
    description: "This table contains information about hospital branches, including branch name, department, and total revenue."
    columns:
      - name: branch_id
        description: "Unique identifier for the hospital branch (surrogate key)."
        tests:
          - not_null
          - unique

      - name: hospital_branch
        description: "Name of the hospital branch (e.g., East, West, Central)."
        tests:
          - not_null

      - name: department
        description: "Department within the hospital (e.g., General, ER, Neurology, etc.)."
        tests:
          - not_null

      - name: total_revenue
        description: "Total revenue generated by the hospital branch across all visits."
        tests:
          - not_null
          - relationships:
              to: ref('fact_revenue')  # Ensures that total_revenue exists in fact_revenue (fact table)

