version: 2

sources:
  - name: staging_data
    schema: public
    tables:
      - name: staging_patient_visits
        description: "Raw data that is loaded from the CSV"
        columns:
          - name: row_id  # Update to match actual column name
            description: "Unique identifier for each patient visit."
            tests:
              - not_null
              - unique
          - name: patient_id
            description: "Unique identifier for each patient."
            tests:
              - not_null
          - name: doctor  # Update to match actual column name
            description: "Unique identifier for each doctor."
            tests:
              - not_null